# Generated by Django 5.1.2 on 2024-10-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seasense_backend", "0002_state_beaches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
