# Generated by Django 5.1.2 on 2024-10-28 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seasense_backend", "0003_alter_region_name"),
    ]

    operations = []
